
import {
  MessageSquare,
  Package,
  Calculator,
  Send,
  Bot,
  Cake,
  Repeat,
  Tag,
  Archive,
  Home,
  type LucideIcon,
  Users,
  LayoutGrid,
  Settings2,
  BarChart,
  Settings,
  FileText,
  LifeBuoy,
  User,
  Shield,
  ImageIcon,
  Code,
  Wallet,
  Wand2,
  Star,
  Sprout,
  Image,
  Info,
  Link,
  Lock,
  Mail,
  MapPin,
  Menu,
  Moon,
  Sun,
  Heart,
  Globe,
  Grid,
  Filter,
  File,
  ExternalLink,
  Download,
  Database,
  Copy,
  Clock,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Check,
  Calendar,
  Briefcase,
  BookOpen,
  Bell,
  Award,
  ArrowRight,
  ArrowLeft,
  AlertTriangle,
  Activity,
  UserPlus,
  Truck,
  ThumbsUp,
  CreditCard,
  Users2,
  Palette,
  PanelLeft,
  Smartphone,
  PlusCircle,
  Bolt,
  ShieldCheck,
  Printer,
} from 'lucide-react';

export interface MenuItem {
  id: string;
  title: string;
  href: string;
  icon: LucideIcon;
  description?: string;
  access?: 'all' | 'admin';
  comingSoon?: boolean;
  iconName?: string; // Added for serialization
}

export const homeMenuItem: MenuItem = {
  id: 'home',
  title: 'Beranda',
  href: '/',
  icon: Home,
  description: 'Kembali ke halaman utama.',
  access: 'all',
}

export const menuItems: MenuItem[] = [
  {
    id: 'laporan-smw-merr',
    title: 'Laporan Harian',
    href: '/laporan-smw-merr',
    icon: MessageSquare,
  },
  {
    id: 'digital-products',
    title: 'Produk Digital',
    href: '/digital-products',
    icon: Wallet,
  },
  {
    id: 'stok-produk',
    title: 'Stok Produk',
    href: '/stok-produk',
    icon: Package,
  },
  {
    id: 'smw-manyar',
    title: 'SMW Manyar',
    href: '/smw-manyar',
    icon: FileText,
  },
  {
    id: 'wa-sender',
    title: 'WA Sender',
    href: '/wa-sender',
    icon: Printer,
  },
  {
    id: 'nexus-ai',
    title: 'Nexus AI',
    href: '/ai-assistant',
    icon: Bot,
  },
  {
    id: 'cek-usia',
    title: 'Cek Usia',
    href: '/cek-usia',
    icon: Cake,
  },
  {
    id: 'kalkulator',
    title: 'Kalkulator',
    href: '/kalkulator',
    icon: Calculator,
    comingSoon: true,
  },
  {
    id: 'convert',
    title: 'Konversi',
    href: '/convert',
    icon: Repeat,
    comingSoon: true,
  },
  {
    id: 'diskon',
    title: 'Diskon',
    href: '/diskon',
    icon: Tag,
    comingSoon: true,
  },
  {
    id: 'stok-manyar',
    title: 'Stok Manyar',
    href: '/stok-manyar',
    icon: Archive,
    comingSoon: true,
  },
];

export const adminMenuItems: MenuItem[] = [
  {
    id: 'admin-dashboard',
    title: 'Dasbor Admin',
    href: '/admin',
    icon: LayoutGrid,
    description: 'Tampilan ringkasan dan manajemen sistem.',
    access: 'admin',
  },
  {
    id: 'user-management',
    title: 'Manajemen Pengguna',
    href: '/admin/users',
    icon: Users,
    description: 'Kelola pengguna, peran, dan hak akses.',
    access: 'admin',
  },
   {
    id: 'team-management',
    title: 'Manajemen Tim',
    href: '/admin/tim',
    icon: Users2,
    description: 'Kelola anggota tim yang ditampilkan.',
    access: 'admin',
  },
   {
    id: 'daily-report-management',
    title: 'Laporan Harian',
    href: '/admin/daily-reports',
    icon: FileText,
    description: 'Kelola semua laporan keuangan harian.',
    access: 'admin',
  },
  {
    id: 'smw-manyar-management',
    title: 'Manajemen SMW Manyar',
    href: '/admin/smw-manyar',
    icon: FileText,
    description: 'Kelola item dan pengaturan untuk laporan SMW Manyar.',
    access: 'admin',
  },
   {
    id: 'digital-product-management',
    title: 'Manajemen Produk',
    href: '/admin/digital-products',
    icon: Package,
    description: 'Kelola produk digital seperti pulsa, data, dll.',
    access: 'admin',
  },
  {
    id: 'digiflazz-integration',
    title: 'Integrasi Digiflazz',
    href: '/admin/digiflazz',
    icon: CreditCard,
    description: 'Kelola koneksi API dan sinkronisasi produk.',
    access: 'admin',
  },
  {
    id: 'menu-management',
    title: 'Manajemen Menu',
    href: '/admin/menus',
    icon: Settings,
    description: 'Sesuaikan item menu utama (grid).',
    access: 'admin',
  },
  {
    id: 'sidebar-management',
    title: 'Manajemen Sidebar',
    href: '/admin/sidebar',
    icon: PanelLeft,
    description: 'Sesuaikan item menu di sidebar utama.',
    access: 'admin',
  },
    {
    id: 'banner-management',
    title: 'Manajemen Banner',
    href: '/admin/banner',
    icon: ImageIcon,
    description: 'Kelola banner dan slide di halaman utama.',
    access: 'admin',
  },
  {
    id: 'branding-settings',
    title: 'Pengaturan Tampilan',
    href: '/admin/branding',
    icon: Palette,
    description: 'Sesuaikan logo, nama, dan ikon aplikasi.',
    access: 'admin'
  },
  {
    id: 'developer-settings',
    title: 'Pengaturan Developer',
    href: '/admin/developer',
    icon: Code,
    description: 'Kelola informasi pada halaman developer.',
    access: 'admin',
  },
  {
    id: 'terms-settings',
    title: 'Syarat & Ketentuan',
    href: '/admin/terms',
    icon: FileText,
    description: 'Kelola konten halaman Syarat & Ketentuan.',
    access: 'admin',
  },
  {
    id: 'session-management',
    title: 'Manajemen Sesi',
    href: '/admin/sessions',
    icon: Lock,
    description: 'Kelola sesi pengguna yang aktif.',
    access: 'admin',
  },
  {
    id: 'firestore-rules',
    title: 'Aturan Firestore',
    href: '/admin/rules',
    icon: ShieldCheck,
    description: 'Salin dan kelola aturan keamanan database.',
    access: 'admin',
  },
  {
    id: 'system-settings',
    title: 'Pengaturan Sistem',
    href: '/admin/setup',
    icon: Settings2,
    description: 'Tutorial integrasi dan konfigurasi sistem.',
    access: 'admin',
  },
];


export const allMenuItems: MenuItem[] = [
  homeMenuItem,
  {
    id: 'profile',
    title: 'Profil',
    href: '/profile',
    icon: User,
    access: 'all',
  },
  {
    id: 'laporan-smw-merr-sidebar',
    title: 'Laporan Harian',
    href: '/laporan-smw-merr',
    icon: MessageSquare,
    access: 'all',
  },
  {
    id: 'digital-products-sidebar',
    title: 'Produk Digital',
    href: '/digital-products',
    icon: Wallet,
    access: 'all',
  },
  {
    id: 'top-up',
    title: 'Top Up Saldo',
    href: '/top-up',
    icon: PlusCircle,
    access: 'all'
  },
  {
    id: 'ai-assistant',
    title: 'Asisten AI Nexus',
    href: '/ai-assistant',
    icon: Bot,
    description: 'Bantuan cerdas untuk tugas Anda.',
    access: 'all',
  },
  {
    id: 'analytics',
    title: 'Analitik',
    href: '/analytics',
    icon: BarChart,
    description: 'Lihat dasbor dan laporan analitik.',
    access: 'all',
  },
  {
    id: 'admin-panel',
    title: 'Panel Admin',
    href: '/admin',
    icon: Shield,
    access: 'admin',
  },
];


// This is a list of all available icons for the icon picker.
// We are using a selection of icons from lucide-react.
export const allIcons: { [key: string]: LucideIcon } = {
  Activity,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowRight,
  Award,
  BarChart,
  Bell,
  BookOpen,
  Bot,
  Briefcase,
  Calculator,
  Calendar,
  Cake,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Code,
  Copy,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  File,
  FileText,
  Filter,
  Globe,
  LayoutGrid, // Renamed from grid to avoid conflict
  Heart,
  Home,
  Image,
  ImageIcon, // Renamed to avoid conflict
  Info,
  Link,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  Moon,
  Package,
  Palette,
  PanelLeft,
  PlusCircle,
  Printer,
  Repeat,
  Send,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  Smartphone,
  Sprout,
  Star,
  Sun,
  Tag,
  ThumbsUp,
  Truck,
  User,
  UserPlus,
  Users,
  Users2,
  Wallet,
  Wand2,
  Bolt,
};

export const allIconsMap: { id: string, icon: LucideIcon }[] = Object.entries(allIcons).map(([id, icon]) => ({
    id: icon.displayName?.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase() || id,
    icon
}));
