
import {
  MessageSquare,
  Package,
  Calculator,
  Send,
  Bot,
  Cake,
  Repeat,
  Tag,
  Archive,
  Home,
  type LucideIcon,
  Users,
  LayoutGrid,
  Settings2,
  BarChart,
  Settings,
  FileText,
  LifeBuoy,
  User,
  Shield,
  ImageIcon,
  Code,
  Wallet,
  Wand2,
  Star,
  Sprout,
  Image,
  Info,
  Link,
  Lock,
  Mail,
  MapPin,
  Menu,
  Moon,
  Sun,
  Heart,
  Globe,
  Grid,
  Filter,
  File,
  ExternalLink,
  Download,
  Database,
  Copy,
  Clock,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Check,
  Calendar,
  Briefcase,
  BookOpen,
  Bell,
  Award,
  ArrowRight,
  ArrowLeft,
  AlertTriangle,
  Activity,
  UserPlus,
  Truck,
  ThumbsUp,
  CreditCard,
  Users2,
  Palette,
  PanelLeft,
  Smartphone,
  PlusCircle,
  Bolt,
  ShieldCheck,
  Printer,
  Github,
  Linkedin,
  UsersRound,
} from 'lucide-react';

export interface MenuItem {
  id: string;
  title: string;
  href: string;
  icon: LucideIcon;
  description?: string;
  access?: 'all' | 'admin';
  comingSoon?: boolean;
  badgeText?: string;
  iconName?: string; // Added for serialization
  isUnderMaintenance?: boolean;
  requiresAuth?: boolean; // Added for login requirement
}

export const homeMenuItem: MenuItem = {
  id: 'home',
  title: 'Beranda',
  href: '/',
  icon: Home,
  description: 'Kembali ke halaman utama.',
  access: 'all',
  requiresAuth: false,
}

export const menuItems: MenuItem[] = [
  {
    id: 'laporan-smw-merr',
    title: 'Laporan Harian',
    href: '/laporan-smw-merr',
    icon: MessageSquare,
    requiresAuth: true,
  },
  {
    id: 'digital-products',
    title: 'Produk Digital',
    href: '/digital-products',
    icon: Wallet,
    requiresAuth: true,
  },
  {
    id: 'stok-produk',
    title: 'Stok Produk',
    href: '/stok-produk',
    icon: Package,
    requiresAuth: true,
  },
  {
    id: 'smw-manyar',
    title: 'SMW Manyar',
    href: '/smw-manyar',
    icon: FileText,
    requiresAuth: true,
  },
  {
    id: 'nexus-ai',
    title: 'Nexus AI',
    href: '/ai-assistant',
    icon: Bot,
    requiresAuth: true,
  },
  {
    id: 'cek-usia',
    title: 'Cek Usia',
    href: '/cek-usia',
    icon: Cake,
    access: 'all',
    requiresAuth: false,
  },
   {
    id: 'firestore-rules',
    title: 'Update kembali halaman ini',
    href: '/firestore-rules',
    icon: ShieldCheck,
    access: 'all',
    requiresAuth: false,
  },
  {
    id: 'kalkulator',
    title: 'Kalkulator',
    href: '/kalkulator',
    icon: Calculator,
    comingSoon: true,
    requiresAuth: false,
  },
  {
    id: 'convert',
    title: 'Konversi',
    href: '/convert',
    icon: Repeat,
    comingSoon: true,
    requiresAuth: false,
  },
  {
    id: 'diskon',
    title: 'Diskon',
    href: '/diskon',
    icon: Tag,
    comingSoon: true,
    requiresAuth: false,
  },
  {
    id: 'stok-manyar',
    title: 'Stok Manyar',
    href: '/stok-manyar',
    icon: Archive,
    comingSoon: true,
    requiresAuth: true,
  },
];

export const defaultAdminMenuItems: MenuItem[] = [
  {
    id: 'admin-dashboard',
    title: 'Dasbor Admin',
    href: '/admin',
    icon: LayoutGrid,
    description: 'Tampilan ringkasan dan manajemen sistem.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'user-management',
    title: 'Manajemen Pengguna',
    href: '/admin/users',
    icon: Users,
    description: 'Kelola pengguna, peran, dan hak akses.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'user-group-management',
    title: 'Grup Pengguna',
    href: '/admin/user-groups',
    icon: UsersRound,
    description: 'Buat grup dan kelola hak akses menu.',
    access: 'admin',
    requiresAuth: true,
  },
   {
    id: 'team-management',
    title: 'Manajemen Tim',
    href: '/admin/tim',
    icon: Users2,
    description: 'Kelola anggota tim yang ditampilkan.',
    access: 'admin',
    requiresAuth: true,
  },
   {
    id: 'daily-report-management',
    title: 'Laporan Harian',
    href: '/admin/daily-reports',
    icon: FileText,
    description: 'Kelola semua laporan keuangan harian.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'smw-manyar-management',
    title: 'Manajemen SMW Manyar',
    href: '/admin/smw-manyar',
    icon: FileText,
    description: 'Kelola item dan pengaturan untuk laporan SMW Manyar.',
    access: 'admin',
    requiresAuth: true,
  },
   {
    id: 'age-calculation-management',
    title: 'Manajemen Kalkulator Usia',
    href: '/admin/age-calculations',
    icon: Cake,
    description: 'Lihat data penggunaan dari fitur kalkulator usia.',
    access: 'admin',
    requiresAuth: true,
  },
   {
    id: 'digital-product-management',
    title: 'Manajemen Produk',
    href: '/admin/digital-products',
    icon: Package,
    description: 'Kelola produk digital seperti pulsa, data, dll.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'digiflazz-integration',
    title: 'Integrasi Digiflazz',
    href: '/admin/digiflazz',
    icon: CreditCard,
    description: 'Kelola koneksi API dan sinkronisasi produk.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'menu-management',
    title: 'Manajemen Menu',
    href: '/admin/menus',
    icon: Settings,
    description: 'Sesuaikan item menu utama (grid).',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'sidebar-management',
    title: 'Manajemen Sidebar',
    href: '/admin/sidebar',
    icon: PanelLeft,
    description: 'Sesuaikan item menu di sidebar utama.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'admin-sidebar-management',
    title: 'Manajemen Sidebar Admin',
    href: '/admin/admin-sidebar',
    icon: PanelLeft,
    description: 'Sesuaikan item menu di sidebar admin.',
    access: 'admin',
    requiresAuth: true,
  },
    {
    id: 'banner-management',
    title: 'Manajemen Banner',
    href: '/admin/banner',
    icon: ImageIcon,
    description: 'Kelola banner dan slide di halaman utama.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'branding-settings',
    title: 'Pengaturan Tampilan',
    href: '/admin/branding',
    icon: Palette,
    description: 'Sesuaikan logo, nama, dan ikon aplikasi.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'developer-settings',
    title: 'Pengaturan Developer',
    href: '/admin/developer',
    icon: Code,
    description: 'Kelola informasi pada halaman developer.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'terms-settings',
    title: 'Syarat & Ketentuan',
    href: '/admin/terms',
    icon: FileText,
    description: 'Kelola konten halaman Syarat & Ketentuan.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'session-management',
    title: 'Manajemen Sesi',
    href: '/admin/sessions',
    icon: Lock,
    description: 'Kelola sesi pengguna yang aktif.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'routes-list',
    title: 'Daftar Rute',
    href: '/admin/routes',
    icon: Link,
    description: 'Lihat semua rute halaman aplikasi.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'firestore-rules',
    title: 'Aturan Firestore',
    href: '/admin/rules',
    icon: ShieldCheck,
    description: 'Salin dan kelola aturan keamanan database.',
    access: 'admin',
    requiresAuth: true,
  },
  {
    id: 'system-settings',
    title: 'Pengaturan Sistem',
    href: '/admin/setup',
    icon: Settings2,
    description: 'Tutorial integrasi dan konfigurasi sistem.',
    access: 'admin',
    requiresAuth: true,
  },
];


export const allMenuItems: MenuItem[] = [
  homeMenuItem,
  {
    id: 'profile',
    title: 'Profil',
    href: '/profile',
    icon: User,
    access: 'all',
    requiresAuth: true,
  },
  {
    id: 'laporan-smw-merr-sidebar',
    title: 'Laporan Harian',
    href: '/laporan-smw-merr',
    icon: MessageSquare,
    access: 'all',
    requiresAuth: true,
  },
  {
    id: 'digital-products-sidebar',
    title: 'Produk Digital',
    href: '/digital-products',
    icon: Wallet,
    access: 'all',
    requiresAuth: true,
  },
  {
    id: 'top-up',
    title: 'Top Up Saldo',
    href: '/top-up',
    icon: PlusCircle,
    access: 'all',
    requiresAuth: true,
  },
  {
    id: 'ai-assistant',
    title: 'Asisten AI Nexus',
    href: '/ai-assistant',
    icon: Bot,
    description: 'Bantuan cerdas untuk tugas Anda.',
    access: 'all',
    requiresAuth: true,
  },
  {
    id: 'analytics',
    title: 'Analitik',
    href: '/analytics',
    icon: BarChart,
    description: 'Lihat dasbor dan laporan analitik.',
    access: 'all',
    requiresAuth: true,
  },
  {
    id: 'admin-panel',
    title: 'Panel Admin',
    href: '/admin',
    icon: Shield,
    access: 'admin',
    requiresAuth: true,
  },
];

// SINGLE SOURCE OF TRUTH for all available icons in the app for pickers.
// The key is the string name that will be stored in Firestore.
// The value is the actual Lucide icon component.
export const allIcons: { [key: string]: LucideIcon } = {
  Activity,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowRight,
  Award,
  BarChart,
  Bell,
  Bolt,
  BookOpen,
  Bot,
  Briefcase,
  Cake,
  Calculator,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Code,
  Copy,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  File,
  FileText,
  Filter,
  Github,
  Globe,
  Grid, // Note: This is different from LayoutGrid
  Heart,
  Home,
  Image,
  ImageIcon,
  Info,
  LayoutGrid,
  LifeBuoy,
  Link,
  Linkedin,
  Lock,
  Mail,
  MapPin,
  Menu,
  Moon,
  Package,
  Palette,
  PanelLeft,
  PlusCircle,
  Printer,
  Repeat,
  Send,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  Smartphone,
  Sprout,
  Star,
  Sun,
  Tag,
  ThumbsUp,
  Truck,
  User,
  UserPlus,
  Users,
  Users2,
  UsersRound,
  Wallet,
  Wand2,
};

    

    