
import {
  MessageSquare,
  Package,
  Calculator,
  Send,
  Bot,
  Cake,
  Repeat,
  Tag,
  Archive,
  Home,
  type LucideIcon,
  Users,
  LayoutGrid,
  Settings2,
  BarChart,
  Settings,
  FileText,
  LifeBuoy,
  User,
  Shield,
  ImageIcon,
  Code,
  Wallet,
  Wand2,
  Star,
  Sprout,
  Image,
  Info,
  Link,
  Lock,
  Mail,
  MapPin,
  Menu,
  Moon,
  Sun,
  Heart,
  Globe,
  Grid,
  Filter,
  File,
  ExternalLink,
  Download,
  Database,
  Copy,
  Clock,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Check,
  Calendar,
  Briefcase,
  BookOpen,
  Bell,
  Award,
  ArrowRight,
  ArrowLeft,
  AlertTriangle,
  Activity,
  UserPlus,
  Truck,
  ThumbsUp,
  CreditCard,
  Users2,
  Palette
} from 'lucide-react';

export interface MenuItem {
  id: string;
  title: string;
  href: string;
  icon: LucideIcon;
  description?: string;
  access?: 'all' | 'admin';
  comingSoon?: boolean;
}

export const homeMenuItem: MenuItem = {
  id: 'home',
  title: 'Beranda',
  href: '/',
  icon: Home,
  description: 'Kembali ke halaman utama.',
  access: 'all',
}

export const menuItems: MenuItem[] = [
  {
    id: 'laporan-smw-merr',
    title: 'Laporan Harian',
    href: '/laporan-smw-merr',
    icon: MessageSquare,
  },
  {
    id: 'stok-produk',
    title: 'Stok Produk',
    href: '/stok-produk',
    icon: Package,
  },
  {
    id: 'smw-manyar',
    title: 'SMW Manyar',
    href: '/smw-manyar',
    icon: FileText,
  },
  {
    id: 'kalkulator',
    title: 'Kalkulator',
    href: '/kalkulator',
    icon: Calculator,
    comingSoon: true,
  },
  {
    id: 'wa-smw',
    title: 'WA SMW',
    href: '/wa-smw',
    icon: Send,
    comingSoon: true,
  },
  {
    id: 'nexus-ai',
    title: 'Nexus AI',
    href: '/ai-assistant',
    icon: Bot,
  },
  {
    id: 'cek-usia',
    title: 'Cek Usia',
    href: '/cek-usia',
    icon: Cake,
  },
  {
    id: 'convert',
    title: 'Konversi',
    href: '/convert',
    icon: Repeat,
    comingSoon: true,
  },
  {
    id: 'diskon',
    title: 'Diskon',
    href: '/diskon',
    icon: Tag,
    comingSoon: true,
  },
  {
    id: 'stok-manyar',
    title: 'Stok Manyar',
    href: '/stok-manyar',
    icon: Archive,
    comingSoon: true,
  },
];

export const adminMenuItems: MenuItem[] = [
  {
    id: 'admin-dashboard',
    title: 'Dasbor Admin',
    href: '/admin',
    icon: LayoutGrid,
    description: 'Tampilan ringkasan dan manajemen sistem.',
    access: 'admin',
  },
  {
    id: 'user-management',
    title: 'Manajemen Pengguna',
    href: '/admin/users',
    icon: Users,
    description: 'Kelola pengguna, peran, dan hak akses.',
    access: 'admin',
  },
   {
    id: 'team-management',
    title: 'Manajemen Tim',
    href: '/admin/tim',
    icon: Users2,
    description: 'Kelola anggota tim yang ditampilkan.',
    access: 'admin',
  },
   {
    id: 'daily-report-management',
    title: 'Laporan Harian',
    href: '/admin/daily-reports',
    icon: FileText,
    description: 'Kelola semua laporan keuangan harian.',
    access: 'admin',
  },
  {
    id: 'smw-manyar-management',
    title: 'Manajemen SMW Manyar',
    href: '/admin/smw-manyar',
    icon: FileText,
    description: 'Kelola item dan pengaturan untuk laporan SMW Manyar.',
    access: 'admin',
  },
  {
    id: 'menu-management',
    title: 'Manajemen Menu',
    href: '/admin/menus',
    icon: Settings,
    description: 'Sesuaikan item menu, ikon, dan visibilitas.',
    access: 'admin',
  },
    {
    id: 'banner-management',
    title: 'Manajemen Banner',
    href: '/admin/banner',
    icon: ImageIcon,
    description: 'Kelola banner dan slide di halaman utama.',
    access: 'admin',
  },
  {
    id: 'branding-settings',
    title: 'Pengaturan Tampilan',
    href: '/admin/branding',
    icon: Palette,
    description: 'Sesuaikan logo, nama, dan ikon aplikasi.',
    access: 'admin'
  },
  {
    id: 'developer-settings',
    title: 'Pengaturan Developer',
    href: '/admin/developer',
    icon: Code,
    description: 'Kelola informasi pada halaman developer.',
    access: 'admin',
  },
  {
    id: 'terms-settings',
    title: 'Syarat & Ketentuan',
    href: '/admin/terms',
    icon: FileText,
    description: 'Kelola konten halaman Syarat & Ketentuan.',
    access: 'admin',
  },
  {
    id: 'system-settings',
    title: 'Pengaturan Sistem',
    href: '/admin/setup',
    icon: Settings2,
    description: 'Tutorial integrasi dan konfigurasi sistem.',
    access: 'admin',
  },
];


export const allMenuItems: MenuItem[] = [
  homeMenuItem,
  {
    id: 'profile',
    title: 'Profil',
    href: '/profile',
    icon: User,
    access: 'all',
  },
  {
    id: 'laporan-smw-merr-sidebar',
    title: 'Laporan Harian',
    href: '/laporan-smw-merr',
    icon: MessageSquare,
    access: 'all',
  },
  {
    id: 'ai-assistant',
    title: 'Asisten AI Nexus',
    href: '/ai-assistant',
    icon: Bot,
    description: 'Bantuan cerdas untuk tugas Anda.',
    access: 'all',
  },
  {
    id: 'analytics',
    title: 'Analitik',
    href: '/analytics',
    icon: BarChart,
    description: 'Lihat dasbor dan laporan analitik.',
    access: 'all',
  },
  {
    id: 'admin-panel',
    title: 'Panel Admin',
    href: '/admin',
    icon: Shield,
    access: 'admin',
  },
];


// This is a list of all available icons for the icon picker.
// We are using a selection of icons from lucide-react.
export const allIconsMap: { id: string, icon: LucideIcon }[] = [
  { id: 'activity', icon: Activity },
  { id: 'alert-triangle', icon: AlertTriangle },
  { id: 'archive', icon: Archive },
  { id: 'arrow-left', icon: ArrowLeft },
  { id: 'arrow-right', icon: ArrowRight },
  { id: 'award', icon: Award },
  { id: 'bar-chart', icon: BarChart },
  { id: 'bell', icon: Bell },
  { id: 'book-open', icon: BookOpen },
  { id: 'bot', icon: Bot },
  { id: 'briefcase', icon: Briefcase },
  { id: 'calculator', icon: Calculator },
  { id: 'calendar', icon: Calendar },
  { id: 'cake', icon: Cake },
  { id: 'check', icon: Check },
  { id: 'chevron-down', icon: ChevronDown },
  { id: 'chevron-left', icon: ChevronLeft },
  { id: 'chevron-right', icon: ChevronRight },
  { id: 'chevron-up', icon: ChevronUp },
  { id: 'clock', icon: Clock },
  { id: 'code', icon: Code },
  { id: 'copy', icon: Copy },
  { id: 'credit-card', icon: CreditCard },
  { id: 'database', icon: Database },
  { id: 'download', icon: Download },
  { id: 'external-link', icon: ExternalLink },
  { id: 'file', icon: File },
  { id: 'file-text', icon: FileText },
  { id: 'filter', icon: Filter },
  { id: 'globe', icon: Globe },
  { id: 'grid', icon: LayoutGrid }, // Renamed from grid to avoid conflict
  { id: 'heart', icon: Heart },
  { id: 'home', icon: Home },
  { id: 'image', icon: Image },
  { id: 'image-icon', icon: ImageIcon }, // Renamed to avoid conflict
  { id: 'info', icon: Info },
  { id: 'layout-grid', icon: LayoutGrid },
  { id: 'life-buoy', icon: LifeBuoy },
  { id: 'link', icon: Link },
  { id: 'lock', icon: Lock },
  { id: 'mail', icon: Mail },
  { id: 'map-pin', icon: MapPin },
  { id: 'menu', icon: Menu },
  { id: 'message-square', icon: MessageSquare },
  { id: 'moon', icon: Moon },
  { id: 'package', icon: Package },
  { id: 'palette', icon: Palette },
  { id: 'repeat', icon: Repeat },
  { id: 'send', icon: Send },
  { id: 'settings', icon: Settings },
  { id: 'settings-2', icon: Settings2 },
  { id: 'shield', icon: Shield },
  { id: 'sprout', icon: Sprout },
  { id: 'star', icon: Star },
  { id: 'sun', icon: Sun },
  { id: 'tag', icon: Tag },
  { id: 'thumbs-up', icon: ThumbsUp },
  { id: 'truck', icon: Truck },
  { id: 'user', icon: User },
  { id: 'user-plus', icon: UserPlus },
  { id: 'users', icon: Users },
  { id: 'users-2', icon: Users2 },
  { id: 'wallet', icon: Wallet },
  { id: 'wand-2', icon: Wand2 },
];
